import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from '@src/app/app-routing.module';
import { AppComponent } from '@src/app/app.component';
import {FormsModule} from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';
import { LoginComponent } from '@src/app/login/login.component';
import { HomeComponent } from '@src/app/home/home.component'
import { PostComponent } from '@src/app/post/post.component';
import { RegisterComponent } from '@src/app/register/register.component';
import { ViewComponent } from '@src/app/view/view.component';
import { Routes, RouterModule } from '@angular/router';
import { DashboardComponent } from '@src/app/dashboard/dashboard.component';
import { ErrorComponent } from '@src/app/error/error.component';
import { AdminComponent } from '@src/app/admin/admin.component';
import { ShowUsersComponent } from '@src/app/show-users/show-users.component';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { UserProfileComponent } from '@src/app/user-profile/user-profile.component';
import { EditProfileComponent } from '@src/app/edit-profile/edit-profile.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';

const Routes: Routes = [
  { path: 'home/:name', component: HomeComponent },
  { path: '', component: LoginComponent },
  { path: 'post/:name', component: PostComponent },
  { path: 'admin', component: AdminComponent},
  { path: 'register', component: RegisterComponent },
  { path: 'postdetails/:name/:id', component: ViewComponent },
  { path: 'dashboard/accept/:name/:from', component: DashboardComponent},
  { path: 'showusers', component: ShowUsersComponent },
  { path: 'editprofile/:name', component: EditProfileComponent },
  { path: 'profile/:name/:user', component: UserProfileComponent },
  { path: 'error', component: ErrorComponent},
  { path: '**', component: ErrorComponent}
]

@NgModule({
  declarations: [
    AppComponent,
    LoginComponent,
    HomeComponent,
    PostComponent,
    RegisterComponent,
    ViewComponent,
    DashboardComponent, 
    ErrorComponent, 
    AdminComponent, 
    ShowUsersComponent, 
    UserProfileComponent, 
    EditProfileComponent, 
    AutoGeneratedComponent,
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    FormsModule,
    HttpClientModule,
    RouterModule.forRoot(Routes),
    BrowserAnimationsModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
